global:
  scrape_interval: 15s

# Scrape_configs
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["64.226.85.4:9100"]